version: '3.8'

services:
  backend:
    build: .
    ports: 
      - "5000:5000" 
    environment:
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASS=${MONGO_PASS}
      - MONGO_DB_NAME=${MONGO_DB_NAME}
      - MONGO_DB_URL=${MONGO_DB_URL}
      - JWT_SECRET=${JWT_SECRET}
